### ISSUE TITLE
TypeError: Cannot read property 'initializing' of undefined

### ISSUE THREAD

**Issue by doublefx** [PierreBesson/generator-jhipster-banner#2]
Hi, I installed the last jhispter version and jhipster-banner, tried to run it after having created my project and got:

`yo jhipster-banner
TypeError: Cannot read property 'initializing' of undefined
    at addInQueue (C:\Users\doublefx\AppData\Roaming\npm\node_modules\generator-jhipster-banner\node_modules\generator-jhipster\node_modules\yeoman-generator\lib\index.js:609:39)
    at Array.forEach (<anonymous>)
    at C:\Users\doublefx\AppData\Roaming\npm\node_modules\generator-jhipster-banner\node_modules\generator-jhipster\node_modules\yeoman-generator\lib\index.js:624:20
    at new Promise (<anonymous>)
    at child.run (C:\Users\doublefx\AppData\Roaming\npm\node_modules\generator-jhipster-banner\node_modules\generator-jhipster\node_modules\yeoman-generator\lib\index.js:581:21)
    at Environment.runGenerator (C:\Users\doublefx\AppData\Roaming\npm\node_modules\yo\node_modules\yeoman-environment\lib\environment.js:616:22)
    at Environment.run (C:\Users\doublefx\AppData\Roaming\npm\node_modules\yo\node_modules\yeoman-environment\lib\environment.js:603:17)
    at C:\Users\doublefx\AppData\Roaming\npm\node_modules\yo\lib\cli.js:167:11
    at Environment.resolver.lookup (C:\Users\doublefx\AppData\Roaming\npm\node_modules\yo\node_modules\yeoman-environment\lib\resolver.js:73:12)
    at init (C:\Users\doublefx\AppData\Roaming\npm\node_modules\yo\lib\cli.js:128:7)`

Any clue?

**Comment by pascalgrimaud** [comment]
it's normal, as this module is not maintained anymore, so it's not compatible with the current version of JHipster

**Comment by pm6422** [comment]
I've tried to use JHipster 4.6, but it failed

**Comment by Karthik-Sivasubramanian** [comment]
so, what is the solution to fix this?

**Comment by pascalgrimaud** [comment]
- fork the project
- find the fix
- commit and push to your fork
- propose a pull request

**Comment by pm6422** [comment]
I got the another option. Go to http://patorjk.com/software/taag/#p=display&f=Graffiti&t=Type%20Something%20

Select the ANSI Shadow font

**Comment by Karthik-Sivasubramanian** [comment]
![image](https://user-images.githubusercontent.com/31807003/77225439-4ae0a680-6b6f-11ea-8623-177471f8779d.png)


this is what i see!
