### ISSUE TITLE
Error

### ISSUE THREAD

**Issue by pm6422** [PierreBesson/generator-jhipster-banner#3]
yo jhipster-banner TypeError: Cannot read property 'initializing' of undefined at addInQueue (C:\Users\doublefx\AppData\Roaming\npm\node_modules\generator-jhipster-banner\node_modules\generator-jhipster\node_modules\yeoman-generator\lib\index.js:609:39) at Array.forEach (<anonymous>) at C:\Users\doublefx\AppData\Roaming\npm\node_modules\generator-jhipster-banner\node_modules\generator-jhipster\node_modules\yeoman-generator\lib\index.js:624:20 at new Promise (<anonymous>) at child.run (C:\Users\doublefx\AppData\Roaming\npm\node_modules\generator-jhipster-banner\node_modules\generator-jhipster\node_modules\yeoman-generator\lib\index.js:581:21) at Environment.runGenerator (C:\Users\doublefx\AppData\Roaming\npm\node_modules\yo\node_modules\yeoman-environment\lib\environment.js:616:22) at Environment.run (C:\Users\doublefx\AppData\Roaming\npm\node_modules\yo\node_modules\yeoman-environment\lib\environment.js:603:17) at C:\Users\doublefx\AppData\Roaming\npm\node_modules\yo\lib\cli.js:167:11 at Environment.resolver.lookup (C:\Users\doublefx\AppData\Roaming\npm\node_modules\yo\node_modules\yeoman-environment\lib\resolver.js:73:12) at init (C:\Users\doublefx\AppData\Roaming\npm\node_modules\yo\lib\cli.js:128:7)

**Comment by pascalgrimaud** [comment]
it's normal, as this module is not maintained anymore, so it's not compatible with the current version of JHipster

**Comment by pm6422** [comment]
Do you know which version is fine？

**Comment by pascalgrimaud** [comment]
Look at the package.json:
https://github.com/PierreBesson/generator-jhipster-banner/blob/master/package.json#L26

So it's compatible with generator-jhipster@4.6.0
Now, we are at v6.7.1, so 2 big major versions

**Comment by pm6422** [comment]
I have tried，but it failed. what is the reason？
